### ISSUE TITLE
VGA Pinout

### ISSUE THREAD

**Issue by urish** [J0NTrollston/tt08-VGA-Pong-with-NES-Controllers#1]
Hi Brandon, thanks for your Tiny Tapeout submission!

I noticed the VGA pinout doesn't match the [Tiny VGA Pmod](https://github.com/mole99/tiny-vga). Most Tiny Tapeout VGA projects follow the [recommended pinout](https://tinytapeout.com/specs/pinouts/#vga-output):

```
uo_out[0] - R1
uo_out[1] - G1
uo_out[2] - B1
uo_out[3] - vsync
uo_out[4] - R0
uo_out[5] - G0
uo_out[6] - B0
uo_out[7] - hsync
```

While you don't have to follow the recommendation, switching to the above pinout will make it easier for others to test your design. However, in case you want to enter the [demoscene competition](https://tinytapeout.com/competitions/demoscene/), the above pinout is one of the requirement.

**Comment by J0NTrollston** [comment]
Thanks for the recommendation, I have modified my output to use the Tiny VGA Pmod.

**Comment by urish** [comment]
You're welcome! Don't forget to submit a new revision though https://app.tinytapeout.com
